Project Jeebby {
    database_type: 'MariaDB'
    Note: '''
        ## Jeebby database
        Jeebby database use the structure of Laravel/Jetstream with Teams.
        This base is sufficient enough for this project. This database documentation is 
        divided in four categories: laravel/jetstream, jeebby, storage and monitor.
        Red colors are tables from Laravel, blue tables are from Jetstream, green are from Jeebby/API and purple tables are mixed origins.

        ### Laravel/jetstream
        These tables are from the laravel/jetstream framework.

        ### Jeebby
        These tables belong to the Jeebby platform.

        ### Storage
        Tables for the Storage API.

        ### Monitor
        Tables for the Monitor API.
    '''
}

TableGroup "Laravel Jetstream"
{
    failed_jobs
    migrations
    password_reset_tokens
    personal_access_tokens
    sessions
    teams
    team_invitations
    team_user
    users
}

TableGroup "Jeebby"
{
    flows
}

Table failed_jobs [headercolor: #be4d25]
{
    id "bigint unsigned" [increment]
    uuid varchar(255)
    connection text
    queue text
    payload longtext
    exception longtext
    failed_at timestamp [default: `current_timestamp()`]

    Indexes
    {
        id [pk]
        uuid [name: 'failed_jobs_uuid_unique', unique]
    }
}

Table migrations [headercolor: #be4d25]
{
    id "int unsigned" [increment]
    migration varchar(255)
    batch int

    Indexes
    {
        id [pk]
    }
}

Table password_reset_tokens [headercolor: #be4d25]
{
    email varchar(255)
    token varchar(255)
    created_at timestamp

    Indexes
    {
        email [pk]
    }
}

Table personal_access_tokens [headercolor: #be4d25]
{
    id "bignint unsigned" [pk, increment]
    tokenable_type varchar(255)
    tokenable_id "bigint unsigned"
    name varchar(255)
    token varchar(64)
    abilities text [null]
    last_used_at timestamp [null]
    expires_at timestamp [null]
    created_at timestamp [null]
    updated_at timestamp [null]

    Indexes
    {
        id [pk]
        token [name: 'personal_access_tokens_token_unique', unique]
        (tokenable_type, tokenable_id) [name: 'personal_access_tokens_tokenable_type_tokenable_id_index']
    }
}

Table sessions [headercolor: #087f23]
{
    id varchar(255)
    user_id "bigint unsigned"
    ip_address varchar(45)
    user_agent text
    payload longtext
    last_activity int

    Indexes
    {
        id [pk]
        user_id [name: 'sessions_user_id_index']
        last_activity [name: 'sessions_last_activity_index']
    }
}

Table teams [headercolor: #087f23]
{
    id "bigint unsigned" [increment]
    user_id "bigint unsigned"
    name varchar(255)
    personal_team tinyint(1)
    created_at timestamp [null]
    updated_at timestamp [null]

    Indexes
    {
        id [pk]
        user_id [name: 'teams_user_id_index']
    }
}

Table team_invitations [headercolor: #087f23]
{
    id "bigint unsigned" [increment]
    team_id "bigint unsigned" [ref: > teams.id]
    email varchar(255)
    role varchar(255) [null]
    created_at timestamp [null]
    updated_at timestamp [null]

    Indexes
    {
        id [pk]
        (team_id, email) [name: 'team_invitations_team_id_email_unique', unique]
    }
}

Table team_user [headercolor: #087f23]
{
    id "bigint unsigned" [increment]
    team_id "bigint unsigned"
    user_id "bigint unsigned"
    role varchar(255) [null]
    created_at timestamp [null]
    updated_at timestamp [null]

    Note: 'This is the table that belongs to the Membership model from Jetstream.'

    Indexes
    {
        id [pk]
        (team_id, user_id) [name: 'team_user_team_id_user_id_unique', unique]
    }
}

Table users [headercolor: #9925be]
{
    id "bigint unsigned" [increment]
    name varchar(255)
    email varchar(255)
    email_verified_at timestamp [null]
    password varchar(255)
    two_factor_secret text [null]
    two_factor_recovery_codes text [null]
    two_factor_confirmed_at timestamp [null]
    remember_token varchar(100) [null]
    current_team_id "bigint unsigned" [null]
    profile_photo_path varhcar(2048) [null]
    created_at timestamp [null]
    updated_at timestamp [null]
    jeebby_system tinyint(1) [default: 0, Note: 'Determin if this user is a Jebby system user.']

    Note: '''
    ### Jeebby system user
    If `jeebby_system` is 1, then the name is **Jeebby $rand(6)** and email is **jeebby_$rand(6)@inter.al
    The user is joined to a team and is assigned the role **Jeebby API**. 
    An access token is generated with the API permissions.
    This access token is then used for the flows to write/read to the Jeebby API from Node-RED.
    These are the Output and Storage API nodes.
    '''

    Indexes
    {
        id [pk]
        (email) [name: 'users_email_unique', unique]
    }
}

Table flows [headercolor: #49be25]
{
    id uuid [pk]
}